//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternalsViewer.Internals.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InternalsViewer.Internals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT s.name+&apos;.&apos;+o.name AS Alloc_Unit
        ///FROM   sys.allocation_units au
        ///       INNER JOIN sys.partitions p ON au.container_id = p.partition_id
        ///       INNER JOIN sys.objects o ON p.object_id = o.object_id
        ///       INNER JOIN sys.schemas s ON s.schema_id = o.schema_id
        ///WHERE  au.allocation_unit_id = @allocation_unit_id 的本地化字符串。
        /// </summary>
        internal static string SQL_Allocation_Unit {
            get {
                return ResourceManager.GetString("SQL_Allocation_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT o.object_id
        ///	  ,iau.first_iam_page
        ///      ,s.name AS schema_name
        ///	  ,o.name AS table_name
        ///      ,i.name AS index_name
        ///	  ,is_ms_shipped AS system
        ///      ,p.index_id
        ///      ,i.type AS index_type
        ///      ,iau.type AS allocation_unit_type
        ///	  ,CASE iau.type
        ///			WHEN 1 THEN &apos;Row Data&apos;
        ///			WHEN 2 THEN &apos;LOB Data&apos;
        ///			WHEN 3 THEN &apos;Row Overflow Data&apos;
        ///	   END AS type_description
        ///      ,iau.used_pages
        ///      ,iau.total_pages
        ///FROM   sys.all_objects o
        ///	   INNER JOIN sys.schemas s ON o.schema_id = s.schema [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_Allocation_Units {
            get {
                return ResourceManager.GetString("SQL_Allocation_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT file_id
        ///      ,page_id
        ///      ,is_modified
        ///      ,row_count
        ///      ,free_space_in_bytes
        ///FROM   sys.dm_os_buffer_descriptors WITH (NOLOCK)
        ///WHERE  database_id = DB_ID(@database) 的本地化字符串。
        /// </summary>
        internal static string SQL_Buffer_Pool {
            get {
                return ResourceManager.GetString("SQL_Buffer_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CHECKPOINT 的本地化字符串。
        /// </summary>
        internal static string SQL_Checkpoint {
            get {
                return ResourceManager.GetString("SQL_Checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT compatibility_level FROM sys.databases WHERE name = @name 的本地化字符串。
        /// </summary>
        internal static string SQL_CompatabilityLevel {
            get {
                return ResourceManager.GetString("SQL_CompatabilityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT ISNULL(data_compression, 0) FROM sys.partitions WHERE partition_id = @partition_id 的本地化字符串。
        /// </summary>
        internal static string SQL_Compression {
            get {
                return ResourceManager.GetString("SQL_Compression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT name FROM sys.databases WHERE database_id = @database_id 的本地化字符串。
        /// </summary>
        internal static string SQL_Database {
            get {
                return ResourceManager.GetString("SQL_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT o.object_id
        ///	  ,s.name AS schema_name
        ///	  ,o.name AS table_name
        ///	  ,is_ms_shipped AS system 
        ///FROM   sys.objects o 
        ///	   INNER JOIN sys.schemas s ON o.schema_id = s.schema_id 
        ///WHERE  type IN (&apos;U&apos;,&apos;S&apos;)
        ///ORDER BY is_ms_shipped desc, s.name asc , o.name asc 的本地化字符串。
        /// </summary>
        internal static string SQL_Database_Tables {
            get {
                return ResourceManager.GetString("SQL_Database_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT DB_ID(@DatabaseName) 的本地化字符串。
        /// </summary>
        internal static string SQL_DatabaseId {
            get {
                return ResourceManager.GetString("SQL_DatabaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT   d.database_id
        ///	    ,d.name
        ///        ,SUM(size) AS Size
        ///        ,d.state 
        ///	    ,COUNT(*) AS DataFiles
        ///       ,d.compatibility_level
        ///FROM     sys.databases d  
        ///	     INNER JOIN sys.master_files mf ON d.database_id = mf.database_id 
        ///WHERE    type = 0
        ///GROUP BY d.database_id
        ///		,d.name
        ///		,d.state 
        ///        ,compatibility_level   
        ///ORDER BY d.name 的本地化字符串。
        /// </summary>
        internal static string SQL_Databases {
            get {
                return ResourceManager.GetString("SQL_Databases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT DISTINCT first_page   
        ///      ,root_page
        ///      ,first_iam_page
        ///      ,partition_number
        ///FROM   sys.system_internals_allocation_units iau
        ///       INNER JOIN sys.partitions p ON iau.container_id = p.partition_id
        ///       INNER JOIN sys.indexes    i ON p.object_id = i.object_id
        ///                                      AND
        ///                                      i.index_id   = p.index_id
        ///WHERE p.object_id = OBJECT_ID(@ObjectName) AND ISNULL(i.name, &apos;&apos;) = @IndexName AND iau.type = 1
        ///ORDER BY partition_num [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_EntryPoints {
            get {
                return ResourceManager.GetString("SQL_EntryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT size FROM sys.database_files WHERE file_id = @file_id 的本地化字符串。
        /// </summary>
        internal static string SQL_File_Size {
            get {
                return ResourceManager.GetString("SQL_File_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE #FileStats
        ///            (file_id int
        ///            ,filegroup int  
        ///            ,total_extents int
        ///            ,used_extents int 
        ///            ,name sysname
        ///            ,file_name nchar(520))
        ///INSERT #FileStats EXEC (&apos;dbcc showfilestats&apos;)
        ///		
        ///SELECT df.file_id
        ///      ,df.type
        ///      ,fg.name as filegroup_name
        ///      ,df.name
        ///      ,physical_name
        ///      ,size
        ///      ,total_extents
        ///      ,used_extents
        ///FROM   sys.database_files df
        ///       INNER JOIN sys.filegroups fg ON df.data_space_id = fg [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_Files {
            get {
                return ResourceManager.GetString("SQL_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -- The reason this is necessary is that the key columns are in sys.system_internals_partition_columns
        ///-- but there doesn&apos;&apos;&apos;&apos;t seem to be a link to which column they are. 
        ///-- 
        ///-- Let me know at danny@sqlinternalsviewer.com if you can think of a better way!
        ///WITH IndexColumns AS
        ///(
        ///SELECT ipc.partition_column_id
        ///	  ,i.type
        ///      ,i.index_id
        ///      ,p.object_id
        ///      ,CASE WHEN is_uniqueifier = 1 THEN &apos;Uniqueifier&apos; ELSE ac.name END AS name
        ///      ,ipc.system_type_id
        ///      ,ipc.max_length
        ///      ,ipc.pr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_Index_Columns {
            get {
                return ResourceManager.GetString("SQL_Index_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT ISNULL(OBJECTPROPERTY(OBJECT_ID(@TableName), &apos;TableHasClustIndex&apos;), 0) 的本地化字符串。
        /// </summary>
        internal static string SQL_ObjectHasClusteredIndex {
            get {
                return ResourceManager.GetString("SQL_ObjectHasClusteredIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBCC PAGE({0},{1},{2},{3}) WITH TABLERESULTS 的本地化字符串。
        /// </summary>
        internal static string SQL_Page {
            get {
                return ResourceManager.GetString("SQL_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT CONVERT(BIT, IS_SRVROLEMEMBER(&apos;sysadmin&apos;)) 的本地化字符串。
        /// </summary>
        internal static string SQL_Sysadmin_Check {
            get {
                return ResourceManager.GetString("SQL_Sysadmin_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT CASE WHEN is_uniqueifier = 1 THEN &apos;Uniqueifier&apos;
        ///            WHEN is_dropped     = 1 THEN &apos;(Dropped)&apos;
        ///            ELSE c.name END AS name,
        ///       ISNULL(c.column_id,-1) AS column_id,
        ///       TYPE_NAME(pc.system_type_id) as type_name,
        ///       pc.system_type_id,
        ///       pc.max_length,
        ///       pc.precision,
        ///       pc.scale,
        ///       pc.leaf_offset,
        ///       pc.is_uniqueifier,
        ///       pc.is_dropped,
        ///       pc.leaf_null_bit,
        ///       CONVERT(BIT, 0) AS is_sparse
        ///FROM   sys.allocation_units au
        ///       IN [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_Table_Columns_2005 {
            get {
                return ResourceManager.GetString("SQL_Table_Columns_2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT CASE WHEN is_uniqueifier = 1 THEN &apos;Uniqueifier&apos;
        ///            WHEN is_dropped     = 1 THEN &apos;(Dropped)&apos;
        ///            ELSE c.name END AS name,
        ///       ISNULL(c.column_id,-1) AS column_id,
        ///       TYPE_NAME(pc.system_type_id) as type_name,
        ///       pc.system_type_id,
        ///       pc.max_length,
        ///       pc.precision,
        ///       pc.scale,
        ///       pc.leaf_offset,
        ///       pc.is_uniqueifier,
        ///       pc.is_dropped,
        ///       ISNULL(c.is_sparse, 0) AS is_sparse,
        ///       pc.leaf_null_bit
        ///FROM   sys.allocation_units au
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_Table_Columns_2008 {
            get {
                return ResourceManager.GetString("SQL_Table_Columns_2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT o.object_id
        ///      ,s.name AS schema_name
        ///      ,CASE WHEN i.name IS NULL 
        ///            THEN o.name
        ///            ELSE o.name + &apos;.&apos; + i.name 
        ///       END AS object_name
        ///      ,o.type AS object_type
        ///      ,i.type_desc
        ///      ,i.type AS index_type
        ///      ,i.index_id AS index_id
        ///      ,iau.first_iam_page
        ///      ,iau.root_page
        ///      ,iau.first_page
        ///      ,iau.total_pages
        ///      ,iau.used_pages
        ///      ,iau.data_pages
        ///      ,iau.type AS alloc_unit_type
        ///      ,iau.type_desc
        ///      ,partition_number
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_Table_Info {
            get {
                return ResourceManager.GetString("SQL_Table_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT [Current LSN] AS LSN
        ///      ,REPLACE(SUBSTRING(Operation, 5, LEN(Operation)),&apos;_&apos;,&apos; &apos;) AS Operation
        ///      ,CASE WHEN Context = &apos;LCX_NULL&apos; THEN NULL
        ///      ELSE REPLACE(SUBSTRING(Context, 5, LEN(Context)),&apos;_&apos;,&apos; &apos;) 
        ///      END AS Context
        ///      ,AllocUnitId
        ///      ,AllocUnitName
        ///      ,[Page ID] AS PageId
        ///      ,[Slot ID] AS SlotId
        ///      ,RowFlags
        ///      ,[Num Elements] AS NumElements
        ///      ,[Offset in Row] AS OffsetInRow
        ///      ,[Rowbits First Bit] AS RowbitsFirstBit
        ///      ,[Rowbits Bit Count] AS [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SQL_TransactionLog {
            get {
                return ResourceManager.GetString("SQL_TransactionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT SERVERPROPERTY(&apos;productversion&apos;), size FROM sysfiles WHERE fileid = 1 的本地化字符串。
        /// </summary>
        internal static string SQL_Version {
            get {
                return ResourceManager.GetString("SQL_Version", resourceCulture);
            }
        }
    }
}
